# Generated by Django 5.1 on 2024-08-25 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='referrer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='referral',
            old_name='xp_earned',
            new_name='xp',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='referral',
            name='coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='@Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referred_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='main.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
