name: Django CI

on:
  push:
    branches: [ "deploy" ]
  pull_request:
    branches: [ "deploy" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Build Docker Image and Push to GHCR, Docker Hub, or AWS ECR
      uses: GlueOps/github-actions-build-push-containers@v0.4.1
      with:
        # The Dockerfile filename
        dockerfile: 'TNS/Dockerfile.django'
        # The container registry to push the image to
        registry: ghcr.io
        # The username for authentication to the container registry (defaults to the github.actor)
        registry-username: ${{ github.actor }}
        # Docker image is named after repository
        image_name: ${{ github.repository }}-django
        context: TNS
              
